---
title: "PCA and the Deprivation Index"
output: html_notebook
---


# Compute the PCs of the geospatial SDOH variables

```{r}
library(tidycensus)
library(tidyverse)
directory <- 'out'
variables <- load_variables(
  year=2020,
  dataset = c("acs5"),
  cache = FALSE
) 
variables <- variables %>% mutate(tablename=sapply(strsplit(variables$name, "\\_"), function(arr) {arr[[1]]})) # comprehensive listing of all variables available in the acs 5 year

```


```{r list rds files}
acs_files <- list.files(directory)
acs_table <- map(acs_files, ~read_rds(file=file.path(directory,.))) %>% bind_rows() # sf file
```

```{r deprivation index}
acs_derived <- acs_table %>% select(starts_with('d_'), "GEOID")
acs_derived <- acs_derived %>% mutate_if(is.numeric, function(x) ifelse(is.infinite(x), 0, x)) %>% na.omit()
acs_derived_geo <- acs_derived %>% select(GEOID)
acs_derived <- acs_derived %>% as_tibble() %>% select(-geometry, -GEOID)
pc_acs <- prcomp(acs_derived, scale.=TRUE)
summary(pc_acs)
```

```{r plot deprivation}
acs_2 <- acs_derived %>% mutate(pc_1=pc_acs$x[,1], pc_2=pc_acs$x[,2], ) %>% cbind(acs_derived_geo)
acs_2 <- acs_2 %>% mutate(composite_index = pc_1*.4 + pc_2*.2) # weight by the variance

p1 <- ggplot(acs_2, aes(d_median_income, pc_1))
p1 <- p1 + geom_point(alpha=.1)
p2 <- ggplot(acs_2, aes(d_education_less_hs_over_25_percentage, pc_1))
p2 <- p2 + geom_point(alpha=.1)
#p3 <- ggplot(acs_2, aes(d_total_male_over_age_65, composite_index)) + geom_point(alpha=.1)

cowplot::plot_grid(p1, p2, p3, nrow=1)

```

# Correlate with disease and general health
```{r}
places <- read_csv("./PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2022_release.csv.zip")
unique(places$Measure)

p_wide <- places %>% select(LocationName, MeasureId, Data_Value) %>% pivot_wider(names_from=MeasureId, values_from = Data_Value) # make in wide format, disease prevalence in each column

acs_2 <- acs_2 %>% left_join(p_wide, by=c("GEOID"="LocationName"))

summary(lm(GHLTH ~ composite_index, acs_2))
p <- ggplot(acs_2, aes(composite_index, GHLTH))
p <- p + geom_point(alpha=.1) + stat_smooth(method = "lm")
p

p <- ggplot(acs_2, aes(composite_index, TEETHLOST))
p <- p + geom_point(alpha=.1) + stat_smooth(method = "lm")
p

```

