Rscript ehec_candidates.R -s AL -y 2015 -g tract
Rscript ehec_candidates.R -s AK -y 2015 -g tract
Rscript ehec_candidates.R -s AZ -y 2015 -g tract
Rscript ehec_candidates.R -s AR -y 2015 -g tract
Rscript ehec_candidates.R -s CA -y 2015 -g tract
Rscript ehec_candidates.R -s CO -y 2015 -g tract
Rscript ehec_candidates.R -s CT -y 2015 -g tract
Rscript ehec_candidates.R -s DE -y 2015 -g tract
Rscript ehec_candidates.R -s DC -y 2015 -g tract
Rscript ehec_candidates.R -s FL -y 2015 -g tract
Rscript ehec_candidates.R -s GA -y 2015 -g tract
Rscript ehec_candidates.R -s HI -y 2015 -g tract
Rscript ehec_candidates.R -s ID -y 2015 -g tract
Rscript ehec_candidates.R -s IL -y 2015 -g tract
Rscript ehec_candidates.R -s IN -y 2015 -g tract
Rscript ehec_candidates.R -s IA -y 2015 -g tract
Rscript ehec_candidates.R -s KS -y 2015 -g tract
Rscript ehec_candidates.R -s KY -y 2015 -g tract
Rscript ehec_candidates.R -s LA -y 2015 -g tract
Rscript ehec_candidates.R -s ME -y 2015 -g tract
Rscript ehec_candidates.R -s MD -y 2015 -g tract
Rscript ehec_candidates.R -s MA -y 2015 -g tract
Rscript ehec_candidates.R -s MI -y 2015 -g tract
Rscript ehec_candidates.R -s MN -y 2015 -g tract
Rscript ehec_candidates.R -s MS -y 2015 -g tract
Rscript ehec_candidates.R -s MO -y 2015 -g tract
Rscript ehec_candidates.R -s MT -y 2015 -g tract
Rscript ehec_candidates.R -s NE -y 2015 -g tract
Rscript ehec_candidates.R -s NV -y 2015 -g tract
Rscript ehec_candidates.R -s NH -y 2015 -g tract
Rscript ehec_candidates.R -s NJ -y 2015 -g tract
Rscript ehec_candidates.R -s NM -y 2015 -g tract
Rscript ehec_candidates.R -s NY -y 2015 -g tract
Rscript ehec_candidates.R -s NC -y 2015 -g tract
Rscript ehec_candidates.R -s ND -y 2015 -g tract
Rscript ehec_candidates.R -s OH -y 2015 -g tract
Rscript ehec_candidates.R -s OK -y 2015 -g tract
Rscript ehec_candidates.R -s OR -y 2015 -g tract
Rscript ehec_candidates.R -s PA -y 2015 -g tract
Rscript ehec_candidates.R -s RI -y 2015 -g tract
Rscript ehec_candidates.R -s SC -y 2015 -g tract
Rscript ehec_candidates.R -s SD -y 2015 -g tract
Rscript ehec_candidates.R -s TN -y 2015 -g tract
Rscript ehec_candidates.R -s TX -y 2015 -g tract
Rscript ehec_candidates.R -s UT -y 2015 -g tract
Rscript ehec_candidates.R -s VT -y 2015 -g tract
Rscript ehec_candidates.R -s VA -y 2015 -g tract
Rscript ehec_candidates.R -s WA -y 2015 -g tract
Rscript ehec_candidates.R -s WV -y 2015 -g tract
Rscript ehec_candidates.R -s WI -y 2015 -g tract
Rscript ehec_candidates.R -s WY -y 2015 -g tract
Rscript ehec_candidates.R -s AS -y 2015 -g tract
Rscript ehec_candidates.R -s GU -y 2015 -g tract
Rscript ehec_candidates.R -s MP -y 2015 -g tract
Rscript ehec_candidates.R -s PR -y 2015 -g tract
Rscript ehec_candidates.R -s UM -y 2015 -g tract
Rscript ehec_candidates.R -s VI -y 2015 -g tract
